version: '2.1'
services:
  youradio:
    image: youradio
    build: .
    environment:
      PORT: 3333
    command: 
      - npm
      - run
      - dev
    volumes: 
      - .:/youradio
      - node_modules:/youradio/node_modules

    ports:
      - 3333:3333

volumes:
  node_modules: {}
